# Generated by Django 5.2.1 on 2025-09-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profilevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='visitor_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='portfolio_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='visitor_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sonstiges',
            name='visitor_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
