# Generated by Django 5.2.1 on 2025-10-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_application_accepted_and_more'),
        ('profiles', '0004_companyprofile_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='Categorys',
            field=models.ManyToManyField(blank=True, related_name='company_Categorys', to='orders.category'),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='Categorys',
            field=models.ManyToManyField(blank=True, related_name='freelancer_Categorys', to='orders.category'),
        ),
        migrations.AddField(
            model_name='sonstiges',
            name='Categorys',
            field=models.ManyToManyField(blank=True, related_name='sonstiges_Categorys', to='orders.category'),
        ),
    ]
