# Generated by Django 5.2.1 on 2025-10-13 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lead'),
        ('orders', '0005_remove_application_accepted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.ManyToManyField(blank=True, to='orders.category')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
