# Generated by Django 5.2.1 on 2025-09-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_userplan_booster_count_userplan_discount_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userplan',
            name='booster_count',
        ),
        migrations.RemoveField(
            model_name='userplan',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='userplan',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userplan',
            name='price',
        ),
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='discount_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
