# Generated by Django 5.2.1 on 2025-10-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_remove_userplan_booster_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
