"""
Django settings for auftragnetz project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import environ
from django.utils.translation import gettext_lazy as _
env = environ.Env()
environ.Env.read_env()  # Dies liest die geheime .env-Datei


# Lade Umgebungsvariablen aus der .env-Datei (falls vorhanden)
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%asqllbecg_+w(*$k*p3wbp21tl6^h7wts^lrn*8h934d)_nzj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "crispy_forms",
    "widget_tweaks",
    "rest_framework",
    "accounts",
    "profiles",
    "orders",
    "plans",
    "products",
    "core",
    "oauth2_provider",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
]

AUTHENTICATION_BACKENDS = [
    "accounts.backends.EmailOrUsernameModelBackend",
    "django.contrib.auth.backends.ModelBackend",  # fallback
]

# settings.py
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # oder was du verwendest
SESSION_COOKIE_SECURE = False  # für lokale Entwicklung
SESSION_COOKIE_SAMESITE = 'Lax'

ROOT_URLCONF = "auftragnetz.urls"
TEMPLATES = [{ "BACKEND":"django.template.backends.django.DjangoTemplates",
    "DIRS":[BASE_DIR / "templates"], "APP_DIRS": True, "OPTIONS": {"context_processors":[
        "django.template.context_processors.debug","django.template.context_processors.request",
        "django.contrib.auth.context_processors.auth","django.contrib.messages.context_processors.messages"]}}]

WSGI_APPLICATION = "auftragnetz.wsgi.application"

DATABASES = {
    'default': env.db(),  # Liest die DATABASE_URL aus der .env Datei
}

AUTH_USER_MODEL = "accounts.User"

USE_I18N = True
USE_L10N = True
LANGUAGE_CODE = 'de'   # Default
LANGUAGES = [
    ('de', 'Deutsch'),
    ('en', 'English'),
    ('fr', 'Français'),
]

TIME_ZONE = "Europe/Berlin"
# Standard static URL
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

# Optional: zusätzliche Verzeichnisse für statische Dateien (z. B. im Projektordner)
import os
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Email (dev) - configure in .env for production
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND")
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS") == "True"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")

AUTHENTICATION_BACKENDS = (
    'oauth2_provider.backends.OAuth2Backend',
    'django.contrib.auth.backends.ModelBackend',
)

SSO_SHARED_SECRET = "Iay01SJILCeOtgo99wjdEf3b6kBULkYMD6e5mfiqZHGIdAUUs9uOvOcgF9utVRVp7oVL9bIDH9MdYLWMIuUk3ECmhFd7hXtfRiPDL0Eu2DffIjrIYD1bJkZgzzbBv9C5E9Fosg6aBu1mEliHcG39wYTbbdRk7YzyEEW7uvjRdDkWSeAtXuKHkm"

JOEL_CLIENT_ID = "JYQgmcexNerZk2KqvFdhCpwtZIA5ljGaM60qiS1Y"
JOEL_REDIRECT_URI = "http://127.0.0.1:8000/auth/joel/callback/"
JOEL_CLIENT_SECRET = "pbkdf2_sha256$1000000$4L8DGdVkw3sW5h3cvWE8iT$oYdRIQGjPyjrnOMw3E9RdgjfF0gbG3RKoUDOiocDAA0="

# SSO Konfiguration
# SSO Konfiguration
SSO_PROVIDER_URL = "https://joel-digitals.de"  # Oder http://127.0.0.1:8001 für lokal
SSO_CLIENT_ID = "JYQgmcexNerZk2KqvFdhCpwtZIA5ljGaM60qiS1Y"
SSO_CLIENT_SECRET = "pbkdf2_sha256$1000000$4L8DGdVkw3sW5h3cvWE8iT$oYdRIQGjPyjrnOMw3E9RdgjfF0gbG3RKoUDOiocDAA0="
SSO_CALLBACK_URL = "https://auftragnetz.de/accounts/register/callback/"  # Für Produktion

IMGBB_API_KEY = os.getenv("IMGBB_API_KEY")

# Session Settings
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # oder 'cached_db'
SESSION_COOKIE_AGE = 1209600  # 2 Wochen
SESSION_SAVE_EVERY_REQUEST = False
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'  # WICHTIG für Cross-Domain!

# Für Development (localhost + .local)
SESSION_COOKIE_DOMAIN = None  # NICHT setzen für localhost!

# Twilio configs via env:
TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID", "")
TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN", "")
TWILIO_FROM = os.getenv("TWILIO_FROM", "")


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/


TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]