# Generated by Django 5.2.1 on 2025-09-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_category_order_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='category',
        ),
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.ManyToManyField(blank=True, to='orders.category'),
        ),
    ]
